[package]
name = "light-rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.2.1"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
solana-client = { path = "../client" }
tokio = { version = "1.14.1", features = ["full"]} 
